### 200
POST http://localhost:5000/api/phones/1/preorders
Content-Type: application/json

{
    "phoneId": 1,
    "customerName": "Олена Пчілка",
    "customerPhone": "+380123456789",
    "status": "pending"
}

### 404 
POST http://localhost:5000/api/phones/100/preorders
Content-Type: application/json

{
    "phoneId": 1,
    "customerName": "Олена Пчілка",
    "customerPhone": "+380123456789",
    "status": "pending"
}
