### 200 [preorders]

GET http://localhost:5000/api/preorders?page=1&results=5

### status=pending
GET http://localhost:5000/api/preorders?page=1&results=5&status=pending

### status=confirmed
GET http://localhost:5000/api/preorders?page=1&results=5&status=confirmed

### status=done
GET http://localhost:5000/api/preorders?page=1&results=5&status=done